### ISSUE TITLE
I got a size error when training my own data

### ISSUE THREAD

**Issue by liangqiLQ** [arashwan/matrixnet#10]

**Comment by arashwan** [comment]
@liangqiLQ  did you figure it  out? I think you need to set number of classes to 1 in config file.

**Comment by liangqiLQ** [comment]
Thank you for your reply，I have solved the problem，Yesterday, I only changed the categories in config file.The class in MatrixNetscornets.py also needs to be changed.

**Comment by lmomoy** [comment]
请问你是怎么训练自己的数据集的？需要改哪些地方呢，除了你说的两个类别数，还有其它地方需要更改吗，比如db/coco里的self.__data = ‘coco’需要改吗？
