### ISSUE TITLE
run dataset myself 'NoneType' object has no attribute 'shape' in samples/coco.py

### ISSUE THREAD

**Issue by tingggggg** [arashwan/matrixnet#11]
i try to run my dataset to train, anno & img dir put in data/coco/annotations & images like u in readme

it print "training start..." but  stuck at 0% 

and i find that some error in samples/coco.py in cutout
at  center_random = [random.randint(0, image.shape[0]), random.randint(0, image.shape[1])]
error message AttributeError: 'NoneType' object has no attribute 'shape'

i want to know this error is my dataset maybe wrong or somewhere i need to change

thanks~

**Comment by arashwan** [comment]
@tingggggg most probably, your data path is not set properly, so no images were loaded correctly.

**Comment by rra94** [comment]
Closing this as no response from OP. Can be reopened if the issue persists.
