### ISSUE TITLE
dataset for baidu cloud link

### ISSUE THREAD

**Issue by CUIcaicai** [arashwan/matrixnet#5]
could you give a baidu cloud link for the pretrained model,thanks

**Comment by arashwan** [comment]
@CUIcaicai , I tried for sometime to navigate through Baidu website, and I think I was able to upload the files, so here are the links to the files. Please let me know if there is a problem. If you can download the links, I can add these links to the readme file.

MatrixNetAnchors Resnet50
链接: https://pan.baidu.com/s/1LrhqF9o4pYDz68eaefyjYQ 提取码: urkm

MatrixNetAnchors Resnet152
链接: https://pan.baidu.com/s/1MZuebaB3xOakY3mhhEcU0w 提取码: kdgy

MatrixNetCorners Resnet50
链接: https://pan.baidu.com/s/1yG73RLiEOi-2Ipkjb7lSTg 提取码: zfme

MatrixNetCorners Resnet152
链接: https://pan.baidu.com/s/1fb6BiZrhQ5pZtLYL3iQ9hA 提取码: wpi6

**Comment by CUIcaicai** [comment]
thank you very much. the third MatrixNetCorners Resnet50 is error because it is the same as the first MatrixNetAnchors Resnet50. is it?



在 2020-01-14 11:27:49，"arashwan" <notifications@github.com> 写道：

@CUIcaicai , I tried for sometime to navigate through Baidu website, and I think I was able to upload the files, so here are the links to the files. Please let me know if there is a problem. If you can download the links, I can add these links to the readme file.

MatrixNetAnchors Resnet50
链接: https://pan.baidu.com/s/1LrhqF9o4pYDz68eaefyjYQ 提取码: urkm

MatrixNetAnchors Resnet152
链接: https://pan.baidu.com/s/1MZuebaB3xOakY3mhhEcU0w 提取码: kdgy

MatrixNetCorners Resnet50
链接: https://pan.baidu.com/s/1yG73RLiEOi-2Ipkjb7lSTg 提取码: zfme

MatrixNetCorners Resnet152
链接: https://pan.baidu.com/s/1fb6BiZrhQ5pZtLYL3iQ9hA 提取码: wpi6

**Comment by arashwan** [comment]
That's right, here is the correct link,

MatrixNetCorners Resnet50
链接: https://pan.baidu.com/s/1uyyaxlfDPukdPpaz7I-nZA 提取码: vc8h

**Comment by CUIcaicai** [comment]
that is all right,thank you again！！



在 2020-01-15 09:05:20，"arashwan" <notifications@github.com> 写道：

That's right, here is the correct link,

MatrixNetCorners Resnet50
链接: https://pan.baidu.com/s/1uyyaxlfDPukdPpaz7I-nZA 提取码: vc8h
