### ISSUE TITLE
test on demo images

### ISSUE THREAD

**Issue by aligoglos** [arashwan/matrixnet#6]
could you release demo code to test on arbitrary images?

**Comment by arashwan** [comment]
The repo doesn't support currently testing on arbitrary images. As a workaround, you can replace the images in the test folder ('testdev2017') with your images, and the run the test as follows:

python test.py <config_file> --testiter <iter> --split testing

This is will give you the best 100 detections for each image in a json file (results.json). If you want to look at the output detections, you can run the previous command in the debug mode (--debug), and the detections for the first 200 images will be outputted under results directory.

python test.py <config_file> --testiter <iter> --split testing --debug

**Comment by arashwan** [comment]
Ok, I just tried the what I suggested in the previous post, and there is one extra step missing. You need to also replace instances_testdev2017.json file with the following (for each image you specify the path and give an id):

`{"images": [{"file_name": "11111.jpg", "id": "1"}],"categories": [{"supercategory": "person","id": 1,"name": "person"},{"supercategory": "vehicle","id": 2,"name": "bicycle"},{"supercategory": "vehicle","id": 3,"name": "car"},{"supercategory": "vehicle","id": 4,"name": "motorcycle"},{"supercategory": "vehicle","id": 5,"name": "airplane"},{"supercategory": "vehicle","id": 6,"name": "bus"},{"supercategory": "vehicle","id": 7,"name": "train"},{"supercategory": "vehicle","id": 8,"name": "truck"},{"supercategory": "vehicle","id": 9,"name": "boat"},{"supercategory": "outdoor","id": 10,"name": "traffic light"},{"supercategory": "outdoor","id": 11,"name": "fire hydrant"},{"supercategory": "outdoor","id": 13,"name": "stop sign"},{"supercategory": "outdoor","id": 14,"name": "parking meter"},{"supercategory": "outdoor","id": 15,"name": "bench"},{"supercategory": "animal","id": 16,"name": "bird"},{"supercategory": "animal","id": 17,"name": "cat"},{"supercategory": "animal","id": 18,"name": "dog"},{"supercategory": "animal","id": 19,"name": "horse"},{"supercategory": "animal","id": 20,"name": "sheep"},{"supercategory": "animal","id": 21,"name": "cow"},{"supercategory": "animal","id": 22,"name": "elephant"},{"supercategory": "animal","id": 23,"name": "bear"},{"supercategory": "animal","id": 24,"name": "zebra"},{"supercategory": "animal","id": 25,"name": "giraffe"},{"supercategory": "accessory","id": 27,"name": "backpack"},{"supercategory": "accessory","id": 28,"name": "umbrella"},{"supercategory": "accessory","id": 31,"name": "handbag"},{"supercategory": "accessory","id": 32,"name": "tie"},{"supercategory": "accessory","id": 33,"name": "suitcase"},{"supercategory": "sports","id": 34,"name": "frisbee"},{"supercategory": "sports","id": 35,"name": "skis"},{"supercategory": "sports","id": 36,"name": "snowboard"},{"supercategory": "sports","id": 37,"name": "sports ball"},{"supercategory": "sports","id": 38,"name": "kite"},{"supercategory": "sports","id": 39,"name": "baseball bat"},{"supercategory": "sports","id": 40,"name": "baseball glove"},{"supercategory": "sports","id": 41,"name": "skateboard"},{"supercategory": "sports","id": 42,"name": "surfboard"},{"supercategory": "sports","id": 43,"name": "tennis racket"},{"supercategory": "kitchen","id": 44,"name": "bottle"},{"supercategory": "kitchen","id": 46,"name": "wine glass"},{"supercategory": "kitchen","id": 47,"name": "cup"},{"supercategory": "kitchen","id": 48,"name": "fork"},{"supercategory": "kitchen","id": 49,"name": "knife"},{"supercategory": "kitchen","id": 50,"name": "spoon"},{"supercategory": "kitchen","id": 51,"name": "bowl"},{"supercategory": "food","id": 52,"name": "banana"},{"supercategory": "food","id": 53,"name": "apple"},{"supercategory": "food","id": 54,"name": "sandwich"},{"supercategory": "food","id": 55,"name": "orange"},{"supercategory": "food","id": 56,"name": "broccoli"},{"supercategory": "food","id": 57,"name": "carrot"},{"supercategory": "food","id": 58,"name": "hot dog"},{"supercategory": "food","id": 59,"name": "pizza"},{"supercategory": "food","id": 60,"name": "donut"},{"supercategory": "food","id": 61,"name": "cake"},{"supercategory": "furniture","id": 62,"name": "chair"},{"supercategory": "furniture","id": 63,"name": "couch"},{"supercategory": "furniture","id": 64,"name": "potted plant"},{"supercategory": "furniture","id": 65,"name": "bed"},{"supercategory": "furniture","id": 67,"name": "dining table"},{"supercategory": "furniture","id": 70,"name": "toilet"},{"supercategory": "electronic","id": 72,"name": "tv"},{"supercategory": "electronic","id": 73,"name": "laptop"},{"supercategory": "electronic","id": 74,"name": "mouse"},{"supercategory": "electronic","id": 75,"name": "remote"},{"supercategory": "electronic","id": 76,"name": "keyboard"},{"supercategory": "electronic","id": 77,"name": "cell phone"},{"supercategory": "appliance","id": 78,"name": "microwave"},{"supercategory": "appliance","id": 79,"name": "oven"},{"supercategory": "appliance","id": 80,"name": "toaster"},{"supercategory": "appliance","id": 81,"name": "sink"},{"supercategory": "appliance","id": 82,"name": "refrigerator"},{"supercategory": "indoor","id": 84,"name": "book"},{"supercategory": "indoor","id": 85,"name": "clock"},{"supercategory": "indoor","id": 86,"name": "vase"},{"supercategory": "indoor","id": 87,"name": "scissors"},{"supercategory": "indoor","id": 88,"name": "teddy bear"},{"supercategory": "indoor","id": 89,"name": "hair drier"},{"supercategory": "indoor","id": 90,"name": "toothbrush"}]}`

I tried and here is what I got on a sample image (I used an intermediate model, but you should get similar or better results with the models provided in the repo).

![0](https://user-images.githubusercontent.com/25515188/72498945-8e7d0400-37fe-11ea-8956-140f5423f431.jpg)

Try it and let me know if you have a problem.

**Comment by arashwan** [comment]
@aligoglos

**Comment by lmomoy** [comment]
can I save all tested images?

**Comment by arashwan** [comment]
@lmomoy yes,  if you use --debug option in test,  first  200 images will be  saved in the results  directory .. if you want to save all images, you  just need to modify test/coco.py to save all  images instead of the first 200 when debug option is used.

**Comment by lmomoy** [comment]
Thanks for your reply. And it is possible to test images which are without annotations?

**Comment by arashwan** [comment]
@lmomoy Yes, follow instructions above to do inference on unlabelled images.

**Comment by lmomoy** [comment]
thanks, but the process which I need to modify the content of instances_testdev2017.json for each image is time-consuming. It there any simple way? Because I have 10000+ unlabelled images.

**Comment by arashwan** [comment]
@lmomoy you don't need to modify the content of instances_testdev2017.json each time, you can modify 'images' variables in the instructions above to test on many images as follows:
"images": [{"file_name": "1.jpg", "id": "1"}, {"file_name": "2.jpg", "id": "2"}, {"file_name": "3.jpg", "id": "3"}, ............]

**Comment by rra94** [comment]
Closing as no response from OP. CAn be reopened if the issue persists.
