### ISSUE TITLE
What about the speed of matrixnet

### ISSUE THREAD

**Issue by jerrywgz** [arashwan/matrixnet#9]
see title

**Comment by arashwan** [comment]
The inference speed on Titan XP for resnet152 is ~250ms/f for center-based, and ~350ms/f for corner-based detector.

**Comment by jerrywgz** [comment]
What about the size of input, 511?

**Comment by arashwan** [comment]
We have used 512 for training corner-based detector and 640 for center-based .. For test, we resized the max side of the image to 900 for both detectors.

**Comment by jerrywgz** [comment]
Thanks a lot!

**Comment by lmomoy** [comment]
The inference speed is relatively slow, and which part of network leads to the situation?

**Comment by arashwan** [comment]
@lmomoy I think data loading and decoding need to be optimized.

**Comment by rra94** [comment]
Closing this.
